apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: project2-core-app 
spec: 
  selector: 
    matchLabels: 
      app: project2-core-app 
  replicas: 2
  template: 
    metadata: 
      labels: 
        app: project2-core-app 
    spec: 
      containers: 
      - name: project2-core-app 
        image: sahar2012/project2-core-app:v1 
        ports: 
        - containerPort: 5003 
--- 
kind: Service 
apiVersion: v1 
metadata: 
  name: project2-core-app  
  labels:
    run: project2-core-app 
spec: 
  selector: 
    app: project2-core-app 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 5003 
    nodePort: 31214 
  type: NodePort